version: "3"
services:
  slack-bridge:
    image: matrixdotorg/matrix-appservice-slack:latest
    volumes:
      - ./config:/config
    network_mode: "host"

  slack-bridge_db:
    image: postgres:14-alpine
    volumes:
      - slack-bridge-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=slack_bridge
      - POSTGRES_USER=slackbridge_user
      - POSTGRES_PASSWORD=${PG_SLACK_BRIDGE_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C

volumes:
  slack-bridge-db:
